import { type PageRecordConfig } from './types';

export const PAGES: PageRecordConfig[] = [
  {
    id: 'quickstart',
    name: 'Quickstart',
    filename: 'AgnoReact-Quickstart',
    docUrl: 'https://docs.copilotkit.ai/agno/quickstart',
    ideFile: 'frontend/src/app/quickstart/demo-chat/page.tsx',
    startLine: 18,
    endLine: 24,
    demoUrl: 'http://localhost:3000/quickstart/demo-chat',
    prompt: 'Can you tell me a joke?',
    waitAfterPromptMs: 9000,
  },
  {
    id: 'prebuilt-components',
    name: 'Prebuilt Components',
    filename: 'AgnoReact-PrebuiltComponents',
    docUrl: 'https://docs.copilotkit.ai/agno/prebuilt-components',
    ideFile: 'frontend/src/app/prebuilt-components/demo-chat/page.tsx',
    startLine: 59,
    endLine: 94,
    demoUrl: 'http://localhost:3000/prebuilt-components/demo-chat',
    prompt: 'What is CopilotKit?',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'threads-overview',
    name: 'Rich Threads - Overview',
    filename: 'AgnoReact-ThreadsOverview',
    docUrl: 'https://docs.copilotkit.ai/agno/threads',
    ideFile: 'frontend/src/app/threads/page.tsx',
    startLine: 26,
    endLine: 67,
    demoUrl: 'http://localhost:3000/threads',
    prompt: '',
    waitAfterPromptMs: 5000,
  },
  {
    id: 'threads-drawer',
    name: 'Rich Threads - Threads Drawer',
    filename: 'AgnoReact-ThreadsDrawer',
    docUrl: 'https://docs.copilotkit.ai/agno/prebuilt-components/copilot-threads-drawer',
    ideFile: 'frontend/src/app/threads/drawer/demo-chat/page.tsx',
    startLine: 25,
    endLine: 33,
    demoUrl: 'http://localhost:3000/threads/drawer/demo-chat',
    prompt: 'Hello! Can you help me manage tasks?',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'threads-headless',
    name: 'Rich Threads - Headless Threads',
    filename: 'AgnoReact-ThreadsHeadless',
    docUrl: 'https://docs.copilotkit.ai/agno/headless-threads',
    ideFile: 'frontend/src/app/threads/headless/demo-chat/page.tsx',
    startLine: 24,
    endLine: 36,
    demoUrl: 'http://localhost:3000/threads/headless/demo-chat',
    prompt: "Let's start a new discussion.",
    waitAfterPromptMs: 8000,
  },
  {
    id: 'threads-lifecycle',
    name: 'Rich Threads - Thread & History Lifecycle',
    filename: 'AgnoReact-ThreadsLifecycle',
    docUrl: 'https://docs.copilotkit.ai/agno/threads-lifecycle',
    ideFile: 'frontend/src/app/threads/lifecycle/demo-chat/page.tsx',
    startLine: 41,
    endLine: 68,
    demoUrl: 'http://localhost:3000/threads/lifecycle/demo-chat',
    prompt: 'Testing conversation persistence.',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'threads-import',
    name: 'Rich Threads - Synchronize Thread History',
    filename: 'AgnoReact-ThreadsImport',
    docUrl: 'https://docs.copilotkit.ai/agno/threads-import',
    ideFile: 'frontend/src/app/threads/import/page.tsx',
    startLine: 36,
    endLine: 43,
    demoUrl: 'http://localhost:3000/threads/import',
    prompt: '',
    waitAfterPromptMs: 5000,
  },
  {
    id: 'threads-architecture',
    name: 'Rich Threads - Persistence Architecture',
    filename: 'AgnoReact-ThreadsArchitecture',
    docUrl: 'https://docs.copilotkit.ai/agno/premium/threads-explained',
    ideFile: 'frontend/src/app/threads/architecture/page.tsx',
    startLine: 42,
    endLine: 79,
    demoUrl: 'http://localhost:3000/threads/architecture',
    prompt: '',
    waitAfterPromptMs: 5000,
  },
  {
    id: 'programmatic-control',
    name: 'Custom Look and Feel - Programmatic Control',
    filename: 'AgnoReact-ProgrammaticControl',
    docUrl: 'https://docs.copilotkit.ai/agno/programmatic-control',
    ideFile: 'frontend/src/app/custom-look-and-feel/programmatic-control/demo-chat/page.tsx',
    startLine: 72,
    endLine: 85,
    demoUrl: 'http://localhost:3000/custom-look-and-feel/programmatic-control/demo-chat',
    prompt: "What's the weather in Tokyo?",
    waitAfterPromptMs: 8000,
  },
  {
    id: 'inspector',
    name: 'Custom Look and Feel - Inspector',
    filename: 'AgnoReact-Inspector',
    docUrl: 'https://docs.copilotkit.ai/agno/inspector',
    ideFile: 'frontend/src/app/custom-look-and-feel/inspector/demo-chat/page.tsx',
    startLine: 18,
    endLine: 30,
    demoUrl: 'http://localhost:3000/custom-look-and-feel/inspector/demo-chat',
    prompt: 'Hello agent! Testing inspector.',
    waitAfterPromptMs: 6000,
  },
  {
    id: 'slots',
    name: 'Custom Look and Feel - Slots',
    filename: 'AgnoReact-Slots',
    docUrl: 'https://docs.copilotkit.ai/agno/custom-look-and-feel/slots',
    ideFile: 'frontend/src/app/custom-look-and-feel/slots/demo-chat/page.tsx',
    startLine: 67,
    endLine: 112,
    demoUrl: 'http://localhost:3000/custom-look-and-feel/slots/demo-chat',
    prompt: 'Hello from customized slots!',
    waitAfterPromptMs: 7000,
  },
  {
    id: 'headless-ui',
    name: 'Custom Look and Feel - Headless UI',
    filename: 'AgnoReact-HeadlessUI',
    docUrl: 'https://docs.copilotkit.ai/agno/custom-look-and-feel/headless-ui',
    ideFile: 'frontend/src/app/custom-look-and-feel/headless-ui/demo-chat/page.tsx',
    startLine: 19,
    endLine: 33,
    demoUrl: 'http://localhost:3000/custom-look-and-feel/headless-ui/demo-chat',
    prompt: "What's the weather in London?",
    waitAfterPromptMs: 8000,
  },
  {
    id: 'display-only',
    name: 'Generative UI - Display Only Component',
    filename: 'AgnoReact-DisplayOnly',
    docUrl: 'https://docs.copilotkit.ai/agno/generative-ui/your-components/display-only',
    ideFile: 'frontend/src/app/generative-ui/your-components/display-only/demo-chat/page.tsx',
    startLine: 50,
    endLine: 58,
    demoUrl: 'http://localhost:3000/generative-ui/your-components/display-only/demo-chat',
    prompt: 'Show the weather card for Tokyo: 77 degrees, clear',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'interactive',
    name: 'Generative UI - Interactive (Stub)',
    filename: 'AgnoReact-Interactive',
    docUrl: 'https://docs.copilotkit.ai/agno/generative-ui/your-components/interactive',
    ideFile: 'frontend/src/app/generative-ui/your-components/interactive/page.tsx',
    startLine: 1,
    endLine: 17,
    demoUrl: 'http://localhost:3000/generative-ui/your-components/interactive',
    prompt: '',
    waitAfterPromptMs: 5000,
  },
  {
    id: 'tool-rendering',
    name: 'Generative UI - Tool Rendering',
    filename: 'AgnoReact-ToolRendering',
    docUrl: 'https://docs.copilotkit.ai/agno/generative-ui/tool-rendering',
    ideFile: 'frontend/src/app/generative-ui/tool-rendering/demo-chat/page.tsx',
    startLine: 50,
    endLine: 80,
    demoUrl: 'http://localhost:3000/generative-ui/tool-rendering/demo-chat',
    prompt: "What's the weather in Tokyo?",
    waitAfterPromptMs: 8000,
  },
  {
    id: 'frontend-tools',
    name: 'App Control - Frontend Tools',
    filename: 'AgnoReact-FrontendTools',
    docUrl: 'https://docs.copilotkit.ai/agno/frontend-tools',
    ideFile: 'frontend/src/app/frontend-tools/demo-chat/page.tsx',
    startLine: 25,
    endLine: 96,
    demoUrl: 'http://localhost:3000/frontend-tools/demo-chat',
    prompt: 'Say hello to Malaika and change the theme to violet',
    waitAfterPromptMs: 7000,
  },
  {
    id: 'human-in-the-loop',
    name: 'App Control - Human in the Loop',
    filename: 'AgnoReact-HumanInTheLoop',
    docUrl: 'https://docs.copilotkit.ai/agno/human-in-the-loop',
    ideFile: 'frontend/src/components/global-frontend-tools.tsx',
    startLine: 74,
    endLine: 114,
    demoUrl: 'http://localhost:3000/human-in-the-loop/demo-chat',
    prompt: 'Can you show me two good options for a restaurant name?',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'copilot-runtime',
    name: 'Backend - Copilot Runtime',
    filename: 'AgnoReact-CopilotRuntime',
    docUrl: 'https://docs.copilotkit.ai/agno/copilot-runtime',
    ideFile: 'frontend/src/app/backend/copilot-runtime/demo-chat/page.tsx',
    startLine: 16,
    endLine: 52,
    demoUrl: 'http://localhost:3000/backend/copilot-runtime/demo-chat',
    prompt: 'Hello default agent! What is your name?',
    waitAfterPromptMs: 8000,
  },
  {
    id: 'ag-ui',
    name: 'Backend - AG-UI Protocol Stream',
    filename: 'AgnoReact-AgUi',
    docUrl: 'https://docs.copilotkit.ai/agno/ag-ui',
    ideFile: 'frontend/src/app/backend/ag-ui/demo-chat/page.tsx',
    startLine: 70,
    endLine: 100,
    demoUrl: 'http://localhost:3000/backend/ag-ui/demo-chat',
    prompt: "What's the weather in Tokyo?",
    waitAfterPromptMs: 8000,
  },
  {
    id: 'error-debugging',
    name: 'Troubleshooting - Error Debugging & Observability',
    filename: 'AgnoReact-ErrorDebugging',
    docUrl: 'https://docs.copilotkit.ai/agno/troubleshooting/error-debugging',
    ideFile: 'frontend/src/app/troubleshooting/error-debugging/demo-chat/page.tsx',
    startLine: 16,
    endLine: 72,
    demoUrl: 'http://localhost:3000/troubleshooting/error-debugging/demo-chat',
    prompt: 'Testing error reporting pipeline',
    waitAfterPromptMs: 7000,
  },
];
